### ISSUE TITLE
Strange, felica/common.cfg from Japanese ver. doesn't have 014 015&018

### ISSUE THREAD

**Issue by palBazzi** [kormax/osaifu-keitai-google-pixel#1]
Here are felica/common.cfg from Xperia 5III(XQ-BQ42 JP sim free)and Pixel 3(G103B) 
Pixel 3, path: /product/etc/felica/common.cfg
`00000001,100008`
`00000002,000068`
`00000003,com.android.chrome`
`00000004,com.android.vending`
`00000005,1`
`00000010,1`
`00000011,eSE1`
`02020001,3030373030310000000000`
`02030001,0`
`02030002,0`
`02030003,intent:#Intent;action=android.settings.NFC_SETTINGS;end`

Xperia 5III, path: /vendor/etc/felica/common.cfg
`00000001,100008`
`00000002,000068`
`00000003,com.android.chrome`
`00000004,com.android.vending`
`00000005,1`
`00000010,1`
`00000011,eSE1`
`02020001,3030313031300000000000`
`02030001,0`
`02030002,0`
`02030003,intent:#Intent;action=android.settings.NFC_SETTINGS;end`
`00000012,1`
`00000013,1`
`00000016,0001`

**Comment by kormax** [comment]
Interesting. If Osaifu-Keitai works nonetheless, it could be because of an older app that looks into another location or that it detects support in other way. 
The only devices i've confirmed my info with were pixel 6 and newer, and this gist was intended primarily for them. If you have any info on how detection works for old devices, would be interesting to know.

**Comment by kormax** [comment]
I've decided to look at the `isCheckInbound` method again. 
There is in fact an additional if clause that returns success (return false) if ALL of the keys are missing, but the file itself isn't (as in that case it returns an error even earlier). 
```
 public boolean isCheckInbound(Context context) {
        int parseInt;
        Integer num = (Integer) Sg.getValue(Sg.Key.SETTING_SKU_VALUE);
        if (num != null) {
            try {
                return 1 != num.intValue(); # If value 1 result of this expression is false - which means success
            } catch (NumberFormatException unused) {
            }
        }
        String str = (String) Sg.getValue(Sg.Key.SETTING_SKU_URL_VALUE);
        String str2 = (String) Sg.getValue(Sg.Key.SETTING_SKU_KEY_VALUE);
        // This is the clause 
        if (str == null && str2 == null) {
            return false;   // false means success
        }
        Cursor cursor = null;
        ***Cursor code cut to save space, same logic***
}
```

That answers the question. Thanks for pointing it out. Will update gist to reflect on new information.

**Comment by kormax** [comment]
Added related info in e61d8d1458b4d0e6fbdda4299785beb9ee576686.

**Comment by palBazzi** [comment]
Thanks for your working. This is a nice project/discovering.
I am Android JP models‘ user, also want global models can use felica.
