### ISSUE TITLE
Method 3 still works on Android 15 Beta [Pixel 8] (SUICA/ICOCA information) 

### ISSUE THREAD

**Issue by Etienne-bdt** [kormax/osaifu-keitai-google-pixel#13]
Just rooted the phone yesterday while in Japan.
I patched the PixelNFC app.

There is an important thing that needs to be mentioned however :

Non-Japanese Visa and MasterCards do NOT work anymore to charge a SUICA/PASMO card via Google Wallet.
What you can do however is to charge the Card at 7 11 Bank ATMs (you can just leave your phone on the NFC card reader) and charge it with cash. (ATMs and Machines where you need to insert the cards won't work (e.g. Kyoto Subway stations if I'm not mistaken)
At this point, it is hardly worth it any more to root it if you only want to be able to charge it wherever you want, as you most likely will not be able to. If you just want your card on your phone though, definitely go for it, I prefer that over having to reach for my wallet that's 3 times as thick. 😆 

For ICOCAs (as I am staying in Kyoto) you even need a Japanese phone number to create a JR west account and a Japanese VISA/Mastercard card that supports 3D Secure 2.0 : Unless you already have a Japanese Card or a JCB (iirc) the only way to create an ICOCA card is to either : 
- Get a Japanese Card from a Bank (unless you're a permanent resident, good luck with that)
- Get a pre-paid card that supports 3DS2.0 (Line Pay for instance, for which you need a Japanese phone number that can receive SMS -> also good luck with that if you're a tourist).

**Comment by kormax** [comment]
Thanks for reporting!

BTW.

You can technically get a JR WEST account without a real phone number, as it can be created without an SMS check.

Also, interestingly, ICOCA can be freely moved between Apple and Google wallet. The only limitation that exists - is that cross-platform transfer has to happen through ICOCA app.
