### ISSUE TITLE
_Osaifu-Keitai app is used for models for the Japanese market.
Please confirm with the seller whether the device is for the Japanese market._

### ISSUE THREAD

**Issue by LenaWil** [kormax/osaifu-keitai-google-pixel#18]
I get this error when opening the app, I assume that means it isn't supported?

**Comment by kormax** [comment]
This error seems new.

Are you using ROOT and attempting to bypass the limitation? Or are you just opening it on a normal non-JP phone?

**Comment by Originalimoc** [comment]
com.google.android.pixelnfc is not patched or in unmount/denylist(even you disabled "Enforcing Denylist" . Or config is not patched.

**Comment by gszep** [comment]
I am also getting this error. How do I proceed?

**Comment by kormax** [comment]
When asking a question like this, provide at least some info to work with. Like:
- Rooted?
- Applied one of the bypass methods (requires ROOT)?
- Device model.
- OS version.

**Comment by gszep** [comment]
I appreciate the above comment was not much to go on 😅  I have decided to not unlock the bootloader as this causes a lot of security-conscious apps like for banking and government to raise errors and prevent usage. In particular it was disappointing to find out that contactless payments stop working entirely 😱

**Comment by kormax** [comment]
Sadly, there are no known ROOT-less bypass methods at this moment.
