### ISSUE TITLE
method root 2 not work on pixel 

### ISSUE THREAD

**Issue by Gliese129** [kormax/osaifu-keitai-google-pixel#2]
I've tried to modify the common.cfg and remove key 00000014 and 00000015. I also tried 2i, which needs to set 00000018 with value 1. Both did pass the beginning verification but failed when initializing. I think osaifu may check if the common.cfg is modified when initializing

**Comment by kormax** [comment]
Hello. That's interesting. And unfortunate (sorry for your troubles). We have to look into that.

I've written in those methods as Theoretical, as I couldn't verify them myself (as I've already activated osaifu-keitai via method 3), but judging from the analysed code I see no reason why it shouldn't work.

A couple of questions that may help me to analyse or help you with this issue:
- What Pixel model do you use;
- What Android OS;
- What do you mean by beginning verification? The one that prohibits osaifu-keitai app from being opened?
- Do you consider initialization the screen with a progress bar, right?
- Do you have all osaifu-keitai apps installed?
- How did you try to start initialization (via Google Wallet or osaifu-keitai itself)?
- Can you give a print out of your config file? Original and modified. Does the original look exactly the same as the one i've posted in this repo?

**Comment by Gliese129** [comment]
> Hello. That's interesting. And unfortunate (sorry for your troubles). We have to look into that.
> 
> I've written in those methods as Theoretical, as I couldn't verify them myself (as I've already activated osaifu-keitai via method 3), but judging from the analysed code I see no reason why it shouldn't work.
> 
> A couple of questions that may help me to analyse or help you with this issue:
> 
> * What Pixel model do you use;
> * What Android OS;
> * What do you mean by beginning verification? The one that prohibits osaifu-keitai app from being opened?
> * Do you consider initialization the screen with a progress bar, right?
> * Do you have all osaifu-keitai apps installed?
> * How did you try to start initialization (via Google Wallet or osaifu-keitai itself)?
> * Can you give a print out of your config file? Original and modified. Does the original look exactly the same as the one i've posted in this repo?

1. Pixel 6
2. Android 14 UP1A.231005.007
3. The beginning check is the one which checks whether the phone is the Japanese version and shows "This app contains configuration files for services in Japan and has no menu items" message if failed
4. yes. Unfortunately, I forgot to take a screenshot, and once it's initialized successfully, it seems like this problem didn't exist even when I cleared the storage and cache data.
5. yes
6. osaifu-keitai itself
7.  the origin one:
00000001,100008
00000002,000068
00000003,com.android.chrome
00000004,com.android.vending
00000005,1
00000010,1
00000011,eSE1
00000012,1
00000013,1
02020001,3030373031310000000000
02030001,0
02030002,0
02030003,intent:#Intent;action=android.settings.NFC_SETTINGS;end
00000014,content://com.google.android.pixelnfc.provider.DeviceInfoContentProvider/isJapanSku
00000015,is_japan_sku
00000016,0001

the modified one :
00000001,100008
00000002,000068
00000003,com.android.chrome
00000004,com.android.vending
00000005,1
00000010,1
00000011,eSE1
00000012,1
00000013,1
02020001,3030373031310000000000
02030001,0
02030002,0
02030003,intent:#Intent;action=android.settings.NFC_SETTINGS;end
00000014,content://com.google.android.pixelnfc.provider.DeviceInfoContentProvider/isJapanSku
00000015,is_japan_sku
00000016,0001
00000018,1

**Comment by kormax** [comment]
Thanks for the information.

Hm, by the looks of it everything should have been OK. Can't really say anything apart from trying the app patch method or the first one.

> yes. Unfortunately, I forgot to take a screenshot, and once it's initialized successfully, it seems like this problem didn't exist even when I cleared the storage and cache data.

If I read it correctly, you've managed to make an activation in the end? Was it using one of the other methods? 

If you activated successfully, of course you cannot reproduce the set-up screen, as the actual set-up takes place on the secure element chip inside of your device. Data on it persists regardless of system reset and state. My device, for instance, has been unrooted to EU stock (and reset), and I still have a Pasmo and Edy on there. Osaifu-keitai doesn't let me in, but Google Wallet app is happy to display them.

**Comment by Gliese129** [comment]
> Thanks for the information.
> 
> Hm, by the looks of it everything should have been OK. Can't really say anything apart from trying the app patch method or the first one.
> 
> > yes. Unfortunately, I forgot to take a screenshot, and once it's initialized successfully, it seems like this problem didn't exist even when I cleared the storage and cache data.
> 
> If I read it correctly, you've managed to make an activation in the end? Was it using one of the other methods?
> 
> If you activated successfully, of course you cannot reproduce the set-up screen, as the actual set-up takes place on the secure element chip inside of your device. Data on it persists regardless of system reset and state. My device, for instance, has been unrooted to EU stock (and reset), and I still have a Pasmo and Edy on there. Osaifu-keitai doesn't let me in, but Google Wallet app is happy to display them.

yes, I patched pixelnfc and made the function "isDeviceJapanSku" return true for every value

**Comment by kormax** [comment]
Good.

Thanks for confirming that method 3) continues to work. 

I'm gonna add a warning to method 2) later that it may not work, and if someone doesn't want to play around they have to go straight for 3) or 1).

Thanks
