### ISSUE TITLE
Xposed/LSPosed module works

### ISSUE THREAD

**Issue by yjwong** [kormax/osaifu-keitai-google-pixel#3]
Just wanted to confirm that in addition to option 2), an Xposed module to patch `com.google.android.pixelnfc` to intercept the `isDeviceJapanSku` call also works. 

Example code as follows:

```java
    private void hookPixelNFC(final LoadPackageParam lpparam) {
        findAndHookMethod(
            "com.google.android.pixelnfc.provider.DeviceInfoContentProvider",
            lpparam.classLoader,
            "isDeviceJapanSku",
            String.class,
            new XC_MethodReplacement() {
                @Override
                protected Object replaceHookedMethod(MethodHookParam param) throws Throwable {
                    return true;
                }
            }
        );
    }
```

Of course, will need to sideload the missing APKs.

Tested with a Pixel 6 (GB7N6) running Android 14 (UP1A.231005.007).

**Comment by kormax** [comment]
Hello.

I think remember this discussion (if it were you who contacted me about such a possibility before). 

It's great that it works! 

Thanks for the information. I appreciate it.
Will update the repo shortly (or via a pr if you want direct credit for it).

**Comment by jachk96** [comment]
Waht does the LSPosed module / apk name?

**Comment by yjwong** [comment]
I didn't publish the code above as a standalone LSPosed module or APK. It's because my current codebase contains a whole bunch of unrelated workarounds, which aren't really suitable to be published for public use.

However, the code can be directly copied into an LSPosed project, the steps are: https://chatgpt.com/share/67891925-ae40-8007-91c4-5f5c06605133

**Comment by Smallcukamanga** [comment]
First of all: thank you for sharing.

However, I'm so sorry. I can't get it to run. Android Studio shows error messages all the time, so I can't create to module. Could you please create it an share it somehow?

**Comment by kormax** [comment]
Just use this one, it's already ready-made.

https://github.com/jjyao88/unlock-felica-pixel
