### ISSUE TITLE
Success, but Wallet on Quick Tiles become unavailable

### ISSUE THREAD

**Issue by stanleylhs** [kormax/osaifu-keitai-google-pixel#5]
Thank you for this guide!

Using starks' Magisk Module https://github.com/starks/PixelFeliCaMod/ 
Successfully added Suica.

However, Wallet on Quick Tiles become unavailable.
Are there any fix for this?

![image](https://github.com/starks/PixelFeliCaMod/assets/4337525/6776e6ff-8b9b-42cb-8e06-a1412ec8c0aa)

**Comment by kormax** [comment]
Wallet quick tile being unavailable is a "feature" of Japanese version of Google Wallet, sadly not a bug. It's not related to Osaifu-Keitai feature directly.

I'm afraid I don't know of any ways of bypassing it.
