### ISSUE TITLE
Success: Pixel 6A USA -> JPN

### ISSUE THREAD

**Issue by Z3r0Auth** [kormax/osaifu-keitai-google-pixel#6]
Just wanted to put another one up on the success board.
I converted my Pixel 6A using the XDA guide regarding changing a pixel 6 to global version (https://xdaforums.com/t/converting-japanese-pixel-6-to-global-version.4365275/) you listed, manually editing the devinfo.img file with a hex editor (HxD)  
After that, i had to fully power down and power back on (commanded reboots didn't change the sku) and the sku was updated in the regulatory labels.  
  
Once that was met with success, i re-flashed the device with the full os from google, reflashed the orignal boot loader, and re-locked it. Everything's showing as secure and in good shape.  
  
Using a travel router that routes all traffic via a VPN, i was able to setup the phone (sans carrier) and get  all the way through logging in, installing osaifu-keitai and to setting up a suicia card.  
  
This has been an excellent trial run for me, before i try it on my newer daily-carry Pixel 8 and return to Japan sometime next year.

![Screenshot_20231228-134225](https://github.com/kormax/osaifu-keitai-google-pixel/assets/31932208/bb7002a0-92ed-4562-8bff-08642be45006)
![Screenshot_20231228-134506](https://github.com/kormax/osaifu-keitai-google-pixel/assets/31932208/d5542be4-b59b-42c7-bd9d-4e40fd9ba2c2)
![Screenshot_20231228-135014 (1)](https://github.com/kormax/osaifu-keitai-google-pixel/assets/31932208/2c4094c2-d276-4bd2-9084-fb8cd4158627)
![Screenshot_20231228-134534](https://github.com/kormax/osaifu-keitai-google-pixel/assets/31932208/d42a9ee3-7c2d-4b8c-9adf-0a60c4d83cf3)

**Comment by kormax** [comment]
Great! 
Thanks for reporting!
