### ISSUE TITLE
questions from a non-pixel user

### ISSUE THREAD

**Issue by austinjklim** [kormax/osaifu-keitai-google-pixel#7]
Really sorry as I have no information to contribute, i'm guessing that pixel 7a can be "modded" to support felica. But other that shutter sound that you can't turn off / gwallet non available on the quick tiles, are there any differences compared to a global rom?

Would like to know before I get a pixel 7a in the near future. 

Also regarding on Safetynet survival game, are you referring that cat-and-mouse game of updating play intergriry magisk module / changing fingerprints as google keeps banning current existing ones?

**Comment by kormax** [comment]
1) Don't think that there are any other differences, but you should definitely do a bit of your own research on that one, as I can give no guarantees.

2) Should work as it works on all other models.

3) Yes, by that I've meant that root-based solution requires a bit of maintenance to keep working.
