### ISSUE TITLE
Using custom recovery to remove pixelnfc? (Android 12 and below)

### ISSUE THREAD

**Issue by zhaobenny** [kormax/osaifu-keitai-google-pixel#8]
Would using [custom recovery](https://android.stackexchange.com/questions/220851/how-can-i-remove-system-apps-on-my-amazon-fire-7-9th-gen-tablet-using-adb-comman#:~:text=Alternative%20method%20(requires%20a%20recovery%20with%20RW%20access%20to%20the%20/system%20partition)%3A) like TWRP to uninstall `com.google.android.pixelnfc` work for a rootless solution for devices on Android 12 and below?  (Looks like Google made the system partition read-only past Android 13)

Unfortunately, my Android version is too new to try this out.

**Comment by kormax** [comment]
Have no Idea honestly. 

I've assumed that if you tried to lock the boot loader after making a change to that data, it could fail the check and brick (need recovery).

Also didn't have a device on older Android, so wasn't able to test this theory anyway.

**Comment by zhaobenny** [comment]
Ah right, you would still need a locked bootloader for Safetynet.

**Comment by arxdeus** [comment]
@zhaobenny just fyi, with these module u can easily bypass safetynet: https://github.com/Displax/safetynet-fix
