### ISSUE TITLE
Patched com.google.android.pixelnfc

### ISSUE THREAD

**Issue by manelscout4life** [kormax/osaifu-keitai-google-pixel#9]
I unpacked it with apktool but now I'm not sure how to patch it. Could you share a patched version or share how to patch it myself?

**Comment by kormax** [comment]
That was a long time ago so I don't possess that APK anymore. 

General info on what I did is described in this repository (look at folders too). If you're encountering problems, I'd advise to look at ready-to-use solutions, [like this one](https://github.com/jjyao88/unlock-felica-pixel).

**Comment by manelscout4life** [comment]
Thank you. I ended up figuring it out. I was hoping to accomplish this without Root. Even though I can uninstall the original app with adb and shizuku, I couldn't install the new one. I will end up having to Root. I added my device model to the isJapanSku list which should also work.

**Comment by manelscout4life** [comment]
I rooted and used the Magisk method. Flashed the factory images and locked the bootloader and it still works!
![Screenshot_20240126-174459](https://github.com/kormax/osaifu-keitai-google-pixel/assets/2093703/20d88a14-d8be-41ea-952a-c5905533b856)
